services:
  message-board:
    build: .
    container_name: hyper-board
    ports:
      - "0.0.0.0:61989:1989"
    env_file:
      - ./.env
    volumes:
      # Mount the local data directory to the container's data directory for persistence
      - ./data:/app/data
    restart: unless-stopped
